server:
  port: 1000
spring:
  application:
    name: "springsecurity"
  datasource:
    url: "jdbc:mysql://localhost:3306/login"
    username: "root"
    password: "root"
  jpa:
    hibernate:
      ddl-auto: update
#  security:
#    user:
#      name: "Ankit"
#      password: "rahul"
